from setuptools import setup, find_packages

setup(
    name="uhop",
    version="0.1.0",
    author="UHOP Systems",
    author_email="support@uhop.dev",
    description="Universal Hardware Optimization Protocol (UHOP) — AI-powered runtime kernel optimizer for developers.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/uhop-labs/uhop",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "numpy>=1.26.0",
        "torch>=2.2.0",
        "triton>=2.2.0",
        "openai>=1.44.0",
        "deepseek-sdk>=0.2.1",
        "py-cpuinfo>=9.0.0",
        "psutil>=5.9.8",
        "pyopencl>=2024.2",
        "tqdm>=4.66.4",
        "tabulate>=0.9.0",
        "orjson>=3.10.7",
        "filelock>=3.15.0",
        "rich>=13.7.1",
        "coloredlogs>=15.0.1",
        "click>=8.1.7",
        "typing-extensions>=4.12.0",
        "packaging>=24.1",
    ],
    extras_require={
        "dev": ["pytest>=8.3.3", "pytest-benchmark>=4.0.0", "ipython>=8.27.0", "jupyter>=1.1.1"],
        "amd": ["rocm-py>=6.0.1"],
